version: "3.7"

services:
  flask:
    build: ./flask
    container_name: flask
    restart: always
    environment:
     APP_NAME: music-discovery-api
    volumes:
      - ./flask:/app
    expose:
      - 8080

  next:
    build: ./next
    container_name: next
    restart: always
    environment:
     APP_NAME: music-discovery-ui
    volumes:
      - ./next:/app
    expose:
      - 3000

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - 80:80